### ISSUE TITLE
FastLED 3.1.6 also works

### ISSUE THREAD

**Issue by adavidzh** [ledunia/Neopixel-Test#1]
Regarding the recommendation to use `FastLED 3.1.3`, like at https://github.com/ledunia/Neopixel-Test/blob/c5d1e4d99afebfd7eb7018f555511983d035afc8/neopixel_test.ino#L2 I would like to report that this example also works with `FastLED 3.1.6`.

**Comment by ledunia** [comment]
Perfect, thx for your feedback
